id = "siscript"
name = "Siscript"
version = "0.2.0"
schema_version = 1
authors = ["Suleyman"]
description = "Siscript language support for Zed"
repository = "https://github.com/suleyman/projects/siscript"

[lib]
kind = "Rust"
version = "0.7.0"

[language_servers.siscript-lsp]
name = "Siscript LSP"
languages = ["Siscript"]

[grammars.siscript]
repository = "file://./tree-sitter-siscript"
rev = "main"
